### ISSUE TITLE
No siop-oid4vp classes in the new npm package version 0.15.0

### ISSUE THREAD

**Issue by JuergenHoedl** [Sphereon-Opensource/OID4VC#127]
Since the did-auth-siop repo has been moved into the OID4VC, I expected classes like OP, OPBuilder, RP, ... to be included in the @sphereon/oid4vci-client npm package. I have not been able to find any of those in version 0.15.0. Is this intended?

**Comment by nklomp** [comment]
No not yet. The packages have stayed the same for this version (0.15.0). So you still need to keep the current imports from the old location. Soon we will start the actual refactoring of this package, where we will extract into new modules and have more common classes.

This was a first step, where there has been some initial refactor work on the SIOP/VP part only, to not make it depend on DIDs. The next round will be a larger refactor

**Comment by JuergenHoedl** [comment]
Thank you for the clarification
